from . import ir_rule
from . import hr_employee_inherit
from . import mail_channel
from . import project_task
from . import sign_template
from . import res_partner
from . import res_users
from . import crm_lead
from . import sale_order